//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnum
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagnumEntities : DbContext
    {
        public MagnumEntities()
            : base("name=MagnumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<draw_CustomerNumber> draw_CustomerNumber { get; set; }
        public virtual DbSet<draw_Number> draw_Number { get; set; }
        public virtual DbSet<draw_ResultUnpublish> draw_ResultUnpublish { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<OrderItemSplit> OrderItemSplits { get; set; }
        public virtual DbSet<setting_CategoryRate> setting_CategoryRate { get; set; }
    }
}
