//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnum
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemSplit
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Number { get; set; }
        public string CategoryCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
