//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnum
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> Box { get; set; }
        public Nullable<decimal> IBox { get; set; }
        public Nullable<decimal> BaoHead { get; set; }
        public Nullable<decimal> BaoTail { get; set; }
        public Nullable<decimal> SuperA1 { get; set; }
        public Nullable<decimal> SuperA2 { get; set; }
        public Nullable<decimal> SuperA3 { get; set; }
        public Nullable<decimal> SuperA4 { get; set; }
        public Nullable<decimal> SuperA5 { get; set; }
        public Nullable<decimal> SuperA6 { get; set; }
    }
}
